### ISSUE TITLE
404 when referring to FMU SDK

### ISSUE THREAD

**Issue by beutlich** [ghorwin/FMICodeGenerator#43]
The README.md links to [FMU SDK](https://www.qtronic.de/de/fmusdk.html), however that link can no longer be resolved. Additionally, the FMU SDK is deprecated.

**Comment by beutlich** [comment]
Could link to https://github.com/qtronic/fmusdk instead.

**Comment by ghorwin** [comment]
Fixed, thanks for pointing this out.
