### ISSUE TITLE
How to pass parameter to fmu?

### ISSUE THREAD

**Issue by AlexLuya** [ghorwin/FMICodeGenerator#44]
Does FMUChecker provide this feature?Or should I find another checker?

**Comment by ghorwin** [comment]
Of course, just define an FMU variable of type 'parameter'.

**Comment by AlexLuya** [comment]
Thanks,question is how to set value to "parameter" by FMUChecker?

**Comment by ghorwin** [comment]
Don't know FMUChecker in detail... maybe check the documentation of FMUChecker? 

Otherwise use a real FMI Co-Simulation-Master, see for example (https://github.com/ghorwin/MasterSim)[MasterSim].
