### ISSUE TITLE
Dependency List Seems Wrong

### ISSUE THREAD

**Issue by JiMa98** [ghorwin/FMICodeGenerator#49]
Hello, your project includes the ability to automatically generate Dependencies tags under the ModelStructure directory. However, I found that the project only associates all input variables with all output variables (because the dependList does not change during iteration to generate Dependencies), which seems to lead to incorrect dependency generation. Not all output variables depend on all input variables. I wonder if my understanding is correct. Can you answer my question?

**Comment by ghorwin** [comment]
Yes, you are correct. As the code generator does not know anything about the internal functionality of the FMU, the dependency list serves as template to be manually adjusted by the author of the FMI. Currently, the dependency list is very conservative and assumes, as you said, that ALL outputs depend on ALL inputs.

**Comment by ghorwin** [comment]
see added example P_Control_2inputs.input
