### ISSUE TITLE
FMU generation on Windows

### ISSUE THREAD

**Issue by ghorwin** [ghorwin/FMICodeGenerator#8]
Create adapted versions of `build.sh` and `deploy.sh` scripts on Windows using batch scripts.

**Comment by SyedFasihMohiuddin** [comment]
deploy.sh created

**Comment by ghorwin** [comment]
Does not work yet.

7zip syntax fix: target file name "archive.zip" instead of "archive.zip". 

Names in deploy.bat are not correctly changed, yet. --> reopened ticket

**Comment by SyedFasihMohiuddin** [comment]
>>>  7zip syntax working 

>>> Other mentioned changes rectified
